services:
  question-service:
    build:
      dockerfile: Dockerfile
    container_name: question-service
    ports:
      - "8000:8000"  # Question service API
    environment:
      - PORT=8000
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres-service
      - DB_PORT=5432

  postgres-service:
    image: postgres:latest
    container_name: postgres-service
    restart: always
    ports:
      - "5433:5432"  # Postgres database
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d  # Runs populate scripts on first init
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 2s
      retries: 10


