services:
  question-service:
    build:
      dockerfile: Dockerfile
    container_name: question-service
    ports:
      - "8000:8000"  # Question service API
    environment:
      - PORT=8000
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      postgres-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 180s
      timeout: 3s
      retries: 3

  postgres-service:
    image: postgres:latest
    container_name: postgres-service
    restart: always
    ports:
      - "5433:5432"  # Postgres database
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./local-script-db-init:/docker-entrypoint-initdb.d  # Runs populate scripts on first init
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 2s
      retries: 10


