services:
  frontend:
    build:
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - VITE_COLLAB_SERVICE_URL=${VITE_COLLAB_SERVICE_URL}
      - VITE_MATCHING_SERVICE_URL=${VITE_MATCHING_SERVICE_URL}
      - VITE_YJS_WS_URL=${VITE_YJS_WS_URL}
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
    ports:
      - "5173:5173"
