services:
  matching-service:
    build:
      dockerfile: Dockerfile
    container_name: matching-service
    ports:
      - "${PORT}:${PORT}"  # Matching service API
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - QUESTION_SERVICE_URL=${QUESTION_SERVICE_URL}
      - COLLAB_SERVICE_URL=${COLLAB_SERVICE_URL}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${PORT}"]

  redis-service:
    image: redis:latest
    container_name: redis-service
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"  # Redis service for matching
    command: ["redis-server"]
